Repository Proyecto-Integrador-I-ISPC/AquaMovil, pull requests merged in 2025-06, with the labels that each got.

#35 Actualización Directorio
  clases/direccion.py
  clases/pago.py
  clases/servicio.py
  clases/usuarios/cliente.py
  clases/vehiculo.py
Labels: documentation

#36 Feature/astrid
  README.md
Labels: documentation

#38 Corrección archivo README.md
  README.md
Labels: documentation

#46 add: main.py
  main.py
Labels: enhancement

#47 Agregado de parte del código base en main.py
  main.py
Labels: enhancement

#48 Modificación funcionamiento
  clases/usuarios/administrador.py
  clases/usuarios/cliente.py
  clases/usuarios/empleado.py
  main.py
Labels: documentation

#49 Refactorización develop
  clases/__pycache__/direccion.cpython-313.pyc
  clases/usuarios/__pycache__/administrador.cpython-313.pyc
  clases/usuarios/__pycache__/cliente.cpython-313.pyc
  clases/usuarios/__pycache__/empleado.cpython-313.pyc
  clases/usuarios/administrador.py
  main.py
Labels: bug

#50 MERGE DEVELOP INTO MAIN
  README.md
  clases/__pycache__/direccion.cpython-313.pyc
  clases/direccion.py
  clases/pago.py
  clases/pedido.py
  clases/servicio.py
  clases/usuarios/__pycache__/administrador.cpython-313.pyc
  clases/usuarios/__pycache__/cliente.cpython-313.pyc
  clases/usuarios/__pycache__/empleado.cpython-313.pyc
  clases/usuarios/administrador.py
  clases/usuarios/cliente.py
  clases/usuarios/empleado.py
  clases/vehiculo.py
  conceptos/comandosGit.txt
  daily-meetings/descripción-carpeta
  daily-meetings/junio/01-06-2025
  daily-meetings/junio/02-06-2025
  daily-meetings/junio/04-06-2025
  daily-meetings/mayo/10-05-2025
  daily-meetings/mayo/13-05-2025
  daily-meetings/mayo/19-05-2025
  daily-meetings/mayo/21-05-2025
  daily-meetings/mayo/25-05-2025
  daily-meetings/mayo/26-05-2025
  daily-meetings/mayo/27-05-2025
  daily-meetings/mayo/30-05-2025
  daily-meetings/mayo/31-05-2025
  git
  main.py
Labels: enhancement
